- hosts: localhost
  become: true

  tasks:
    - name: Stop old containers
      shell: docker-compose down
      args:
        chdir: /var/lib/jenkins/workspace/devops

    - name: Start containers WITHOUT rebuild
      shell: docker-compose up -d
      args:
        chdir: /var/lib/jenkins/workspace/devops
