- hosts: localhost
  become: true

  tasks:
    - name: Stop old containers
      shell: docker-compose down
      args:
        chdir: /var/lib/jenkins/workspace/devops

    - name: Start new containers
      shell: DOCKER_BUILDKIT=0 docker-compose up -d --build
      args:
        chdir: /var/lib/jenkins/workspace/devops
